routes/web.php
<?php

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

/**
 * Admin panel
 */
Route::group([
    'middleware' => 'auth',
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function () {
    Route::get('/dashboard', [
        'as' => 'index',
        'uses' => 'DashboardController@index',
    ])->middleware('can:reports-dashboard');

    Route::resource('category', 'CategoriesController', [
        'except' => ['show'],
    ]);

    Route::resource('sale', 'SalesController', [
        'only' => 'index',
    ])->middleware('can:management-sales');

    Route::resource('product', 'ProductsController', [
        'except' => ['show'],
    ]);

    Route::resource('role', 'RolesController', [
        'except' => ['show'],
    ])->middleware('can:management-users');

    Route::resource('user', 'UsersController', [
        'except' => ['show'],
    ])->middleware('can:management-users');
});

/**
 * Guest views
 */
Route::group([
    'as' => 'guest.',
], function () {
    Route::get('/', [
        'as' => 'index',
        'uses' => 'IndexController@index',
    ]);

    Route::group([
        'as' => 'product.',
        'prefix' => 'products',
    ], function () {
        Route::get('/', [
            'as' => 'index',
            'uses' => 'ShopController@index',
        ]);

        Route::get('/{product}', [
            'as' => 'show',
            'uses' => 'ShopController@show',
        ]);
    });

    Route::group([
        'as' => 'cart.',
        'prefix' => 'cart',
    ], function () {
        Route::get('/', [
            'as' => 'index',
            'uses' => 'CartController@index',
        ]);

        Route::get('{product}/delete', [
            'as' => 'delete',
            'uses' => 'CartController@destroy',
        ]);

        Route::post('add', [
            'as' => 'add',
            'uses' => 'CartController@add',
        ]);

        Route::post('buy', [
            'as' => 'buy',
            'uses' => 'CartController@buy',
        ]);
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Product.
 *
 * @package namespace App\Models;
 */
class Product extends Model
{
    use Sluggable;

    /**
     * Default photo
     */
    const DEFAULT_PHOTO_PATH = 'thumbnails/product_default.png';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_id',
        'title',
        'slug',
        'description',
        'thumbnail',
        'price',
        'amount',
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title',
            ],
        ];
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * Binding events
     */
    public static function boot()
    {
        parent::boot();

        /**
         * Delete physical file from storage during deleting a row from DB
         */
        static::deleting(function (Product $product) {
            if ($product->thumbnail !== self::DEFAULT_PHOTO_PATH) {
                \Storage::disk('public')->delete($product->thumbnail);
            }
        });
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Sales of current product
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function sales()
    {
        return $this->hasMany(Sale::class);
    }

    /**
     * Get formatted price
     *
     * @return string
     */
    public function getFormattedPriceAttribute()
    {
        return number_format($this->price, 2);
    }

    /**
     * Get formatted price
     *
     * @return string
     */
    public function getFormattedAmountAttribute()
    {
        return number_format($this->amount);
    }
}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductCreateRequest;
use App\Http\Requests\ProductUpdateRequest;
use App\Models\Category;
use App\Models\Product;
use App\Repositories\ProductRepository;
use App\Validators\ProductValidator;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;

/**
 * Class ProductsController.
 *
 * @package namespace App\Http\Controllers;
 */
class ProductsController extends Controller
{
    /**
     * @var ProductRepository
     */
    protected $repository;

    /**
     * @var ProductValidator
     */
    protected $validator;

    /**
     * ProductsController constructor.
     *
     * @param ProductRepository $repository
     * @param ProductValidator $validator
     */
    public function __construct(ProductRepository $repository, ProductValidator $validator)
    {
        parent::__construct();
        $this->repository = $repository;
        $this->validator = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $products = $this->repository->with('category')->paginate();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $products,
            ]);
        }

        return view('products.index', compact('products'));
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create', [
            'categories' => Category::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ProductCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(ProductCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $data = $request->all();
            if ($request->has('thumbnail')) {
                $filePath = $request->file('thumbnail')->store('thumbnails', [
                    'disk' => 'public',
                ]);
                $data['thumbnail'] = $filePath;
            } else {
                $data['thumbnail'] = Product::DEFAULT_PHOTO_PATH;
            }

            $product = $this->repository->create($data);

            $response = [
                'message' => 'Product created.',
                'data' => $product->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('admin.product.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error' => true,
                    'message' => $e->getMessageBag(),
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = $this->repository->with('category')->find($id);
        $categories = Category::all();

        return view('products.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ProductUpdateRequest $request
     * @param  string $product
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(ProductUpdateRequest $request, Product $product)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $data = $request->all();
            if ($request->has('thumbnail')) {
                $filePath = $request->file('thumbnail')->store('thumbnails', [
                    'disk' => 'public',
                ]);
                $data['thumbnail'] = $filePath;
                if ($product->thumbnail !== Product::DEFAULT_PHOTO_PATH) {
                    \Storage::disk('public')->delete($product->thumbnail);
                }
            }

            $product = $this->repository->update($data, $product->id);

            $response = [
                'message' => 'Product updated.',
                'data' => $product->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->route('admin.product.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error' => true,
                    'message' => $e->getMessageBag(),
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Product deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Product deleted.');
    }
}

resources/views/products/create.blade.php
@extends('layouts.admin')

@section('title', 'Creating Product')

@section('main_container')

    <div class="mt-2">
        @include('includes.flash')
    </div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Creating Product</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br/>
                    <form class="form-horizontal form-label-left"
                          method="post"
                          enctype="multipart/form-data"
                          action="{{ route('admin.product.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="category_id">Category <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select id="category_id" name="category_id"
                                        class="form-control col-md-7 col-xs-12"
                                        required>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->title }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="title">Title <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="title" name="title" maxlength="255"
                                       class="form-control col-md-7 col-xs-12"
                                       value="{{ old('title') }}"
                                       required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="description">Description <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea id="description"
                                          name="description"
                                          class="form-control col-md-7 col-xs-12"
                                          required>{{ old('description') }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="thumbnail">Thumbnail
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="file" name="thumbnail" accept="image/*">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="amount">Amount <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="number" min="0" step="1" id="amount" name="amount"
                                       class="form-control col-md-7 col-xs-12"
                                       value="{{ old('amount') }}"
                                       required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="price">Price <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="number" min="0.01" step="0.01" id="price" name="price"
                                       class="form-control col-md-7 col-xs-12"
                                       value="{{ old('price') }}"
                                       required>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <a href="{{ route('admin.product.index') }}" class="btn btn-primary"
                                   type="button">Cancel</a>
                                <button class="btn btn-primary" type="reset">Reset</button>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/products/edit.blade.php
@extends('layouts.admin')

@section('title', 'Editing Product')

@section('main_container')

    <div class="mt-2">
        @include('includes.flash')
    </div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Editing Product</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br/>
                    <form class="form-horizontal form-label-left"
                          method="post"
                          enctype="multipart/form-data"
                          action="{{ route('admin.product.update', $product) }}">
                        {{ csrf_field() }}
                        @method('put')

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="category_id">Category <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select id="category_id" name="category_id"
                                        class="form-control col-md-7 col-xs-12"
                                        required>
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ $product->category->id === $category->id ? 'selected' : '' }}>{{ $category->title }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="title">Title <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" id="title" name="title" maxlength="255"
                                       class="form-control col-md-7 col-xs-12"
                                       value="{{ old('title', $product->title) }}"
                                       required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="description">Description <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <textarea id="description"
                                          name="description"
                                          class="form-control col-md-7 col-xs-12"
                                          required>{{ old('description', $product->description) }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="thumbnail">Thumbnail
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <img src="{{ Storage::url($product->thumbnail) }}"
                                     alt="{{ $product->title }}">
                                <input type="file" name="thumbnail" accept="image/*">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="amount">Amount <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="number" min="0" step="1" id="amount" name="amount"
                                       class="form-control col-md-7 col-xs-12"
                                       value="{{ old('amount', $product->amount) }}"
                                       required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                   for="price">Price <span
                                        class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="number" min="0.01" step="0.01" id="price" name="price"
                                       class="form-control col-md-7 col-xs-12"
                                       value="{{ old('price', $product->price) }}"
                                       required>
                            </div>
                        </div>
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <a href="{{ route('admin.product.index') }}" class="btn btn-primary"
                                   type="button">Cancel</a>
                                <button class="btn btn-primary" type="reset">Reset</button>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/products/index.blade.php
@extends('layouts.admin')

@section('title', 'Products')

@push('stylesheets')
    <!-- Example -->
    <!--<link href=" <link href="{{ asset("css/myFile.min.css") }}" rel="stylesheet">" rel="stylesheet">-->
@endpush

@section('main_container')

    <div class="mt-2">
        @include('includes.flash')
    </div>

    <!-- page content -->
    <div class="col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Products</h2>
                <ul class="nav navbar-right">
                    <li><a href="{{ route('admin.product.create') }}" class="btn btn-success"><i
                                    class="fa fa-plus"></i></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="text-center">
                    {{ $products->render() }}
                </div>
                <table class="products table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Category</th>
                        <th>Description</th>
                        <th>Thumbnail</th>
                        <th>Amount</th>
                        <th>Price</th>
                        <th width="120">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($products as $product)
                        <tr>
                            <th scope="row">{{ $product->id }}</th>
                            <td>{{ $product->title }}</td>
                            <td>{{ $product->category->title }}</td>
                            <td>{{ str_limit($product->description) }}</td>
                            <td>
                                <img class="product-image"
                                     src="{{ Storage::url($product->thumbnail) }}"
                                     alt="{{ $product->title }}">
                            </td>
                            <td>{{ $product->formatted_amount }}</td>
                            <td>$ {{ $product->formatted_price }}</td>
                            <td>
                                <a href="{{ route('admin.product.edit', $product) }}"
                                   class="btn btn-warning"><i
                                            class="fa fa-pencil"></i></a>
                                <form method="post"
                                      action="{{ route('admin.product.destroy', $product) }}"
                                      class="d-inline">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="delete">
                                    <button type="submit" class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr class="text-center">
                            <td colspan="8">
                                <h3>Data is not found</h3>
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
                <div class="text-center">
                    {{ $products->render() }}
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
@endsection