routes/web.php
<?php

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

/**
 * Admin panel
 */
Route::group([
    'middleware' => 'auth',
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
], function () {
    Route::get('/dashboard', [
        'as' => 'index',
        'uses' => 'DashboardController@index',
    ])->middleware('can:reports-dashboard');

    Route::resource('category', 'CategoriesController', [
        'except' => ['show'],
    ]);

    Route::resource('sale', 'SalesController', [
        'only' => 'index',
    ])->middleware('can:management-sales');

    Route::resource('product', 'ProductsController', [
        'except' => ['show'],
    ]);

    Route::resource('role', 'RolesController', [
        'except' => ['show'],
    ])->middleware('can:management-users');

    Route::resource('user', 'UsersController', [
        'except' => ['show'],
    ])->middleware('can:management-users');
});

/**
 * Guest views
 */
Route::group([
    'as' => 'guest.',
], function () {
    Route::get('/', [
        'as' => 'index',
        'uses' => 'IndexController@index',
    ]);

    Route::group([
        'as' => 'product.',
        'prefix' => 'products',
    ], function () {
        Route::get('/', [
            'as' => 'index',
            'uses' => 'ShopController@index',
        ]);

        Route::get('/{product}', [
            'as' => 'show',
            'uses' => 'ShopController@show',
        ]);
    });

    Route::group([
        'as' => 'cart.',
        'prefix' => 'cart',
    ], function () {
        Route::get('/', [
            'as' => 'index',
            'uses' => 'CartController@index',
        ]);

        Route::get('{product}/delete', [
            'as' => 'delete',
            'uses' => 'CartController@destroy',
        ]);

        Route::post('add', [
            'as' => 'add',
            'uses' => 'CartController@add',
        ]);

        Route::post('buy', [
            'as' => 'buy',
            'uses' => 'CartController@buy',
        ]);
    });
});

resources/views/includes/flash.blade.php
@foreach (['info' => 'info', 'warning' => 'warning', 'error' => 'danger', 'success' => 'success', 'message' => 'success'] as $class => $key)
    @if(Session::has($class))
        <div class="alert alert-{{ $key }} fade in alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <h4>{{ Session::get($class) }}</h4>
        </div>
    @endif
@endforeach

@if (isset($errors) && count($errors) > 0)
    <div class="alert alert-danger fade in alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @foreach ($errors->all() as $error)
            <h4><i class="fa fa-exclamation-triangle"></i> {{ $error }}</h4>
        @endforeach
    </div>
@endif

resources/views/includes/footer.blade.php
<footer>
    <div class="pull-right">
        Computer Shop - Powered by <a target="_blank" href="#">Pavel Savushkin</a>
    </div>
    <div class="clearfix"></div>
</footer>

resources/views/includes/sidebar.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="{{ url('/') }}" class="site_title"><i class="fa fa-desktop"></i> <span>Computer Shop!</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile">
            <div class="profile_pic">
                <img src="{{ Gravatar::src(Auth::user()->email) }}"
                     alt="Avatar of {{ Auth::user()->name }}"
                     class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ Auth::user()->name }}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br/>

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Management</h3>
                <ul class="nav side-menu">
                    @if (Gate::allows('reports-dashboard'))
                        <li>
                            <a href="{{ route('admin.index') }}">
                                <i class="fa fa-line-chart"></i>
                                Dashboard
                            </a>
                        </li>
                    @endif
                    @if (Gate::allows('management-sales'))
                        <li>
                            <a href="{{ route('admin.sale.index') }}">
                                <i class="fa fa-money"></i>
                                Sales
                                @if ($todaySales > 0)
                                    <span class="label label-success pull-right">+ {{ $todaySales }}</span>
                                @endif
                            </a>
                        </li>
                    @endif
                    @if (Gate::allows('management-users'))
                        <li><a><i class="fa fa-users"></i> Users <span
                                        class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li><a href="{{ route('admin.role.index') }}">Role</a></li>
                                <li><a href="{{ route('admin.user.index') }}">Users</a></li>
                            </ul>
                        </li>
                    @endif
                    <li><a><i class="fa fa-list-alt"></i> Management <span
                                    class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ route('admin.category.index') }}">Categories</a></li>
                            <li><a href="{{ route('admin.product.index') }}">Products</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            @if (Gate::allows('management-administration'))
                <div class="menu_section">
                    <h3>Extra</h3>
                    <ul class="nav side-menu">
                        <li>
                            <a><i class="fa fa-sitemap"></i> Administration <span
                                        class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li>
                                    <a href="#">Roadmap</a>
                                </li>
                                <li>
                                    <a href="#">Bugs / Offers</a>
                                </li>
                                <li>
                                    <a href="#">Career</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            @endif
        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout"
               href="{{ url('/logout') }}">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

resources/views/includes/topbar.blade.php
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                       aria-expanded="false">
                        <img src="{{ Gravatar::src(Auth::user()->email) }}" alt="Avatar of {{ Auth::user()->name }}">
                        {{ Auth::user()->name }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Profile</a></li>
                        <li>
                            <a href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><a href="javascript:;">Help</a></li>
                        <li><a href="{{ url('/logout') }}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>

                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown"
                       aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">6</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        <li>
                            <a>
                                <span class="image"><img src="{{ Gravatar::src(Auth::user()->email) }}"
                                                         alt="Profile Image"/></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="{{ Gravatar::src(Auth::user()->email) }}"
                                                         alt="Profile Image"/></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="{{ Gravatar::src(Auth::user()->email) }}"
                                                         alt="Profile Image"/></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="{{ Gravatar::src(Auth::user()->email) }}"
                                                         alt="Profile Image"/></span>
                                <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                                <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->